name: "优化建议/Optimization suggestions"
description: "对已有功能的小幅度优化或改进建议/Minor optimization or improvement suggestions for existing functions"
labels: [优化/optimize, 新反馈/new issue]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项/Check list"
    description: "逐个检查下列项目并勾选确认。\nCheck the following items one by one and tick them."
    options:
    - label: "我已知晓 issue 至少使用**中文和英语中的一种**编写，且重要 issue 应该尽量使用双语。\nI know that the issue should be written in at least one of Chinese and English, and for important issue, it should be written in both languages as much as possible."
      required: true
    - label: "EMCLauncher 是**最新版**且**新版本没有实现你所描述述的内容**。\EMCLauncher is the **latest** version and the latest version does not implement the feature you described."
      required: true
    - label: "我已在 [Issues 页面](https://github.com/SALTWOOD/EMCLauncher/issues) 中搜索，确认了这一请求**未被提交过**。\nI have searched on the [Issues page](https://github.com/SALTWOOD/EMCLauncher/issues) and confirmed that this request has not been submitted yet."
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 描述/Description.
    description: "详细描述具体需要优化哪些地方。\nProvide a detailed description of the specific areas that need to be optimized."
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 原因/Reason
    description: "详细描述你为什么需要这项优化。\nDescribe in detail why you need this optimization."
    value: |
      It can help me to...
  validations:
    required: true